package com.comecome.anamnese.models;

public enum Objective {
    PERDA_CONTROLE_PESO,
    GANHO_MASSA_MUSCULAR,
    MELHORA_SAUDE_INTESTINAL,
    FORTALECIMENTO_SISTEMA_IMUNOLOGICO,
    HABITOS_SAUDAVEIS
}
